# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzU1ZjMyZGNmNThlMmYyYmU1YjdlYTNiZDQxYzQ2YzIxMjU4NjYwODYwMzgxZGFmNDUwYTc1MTkzODdhM2Q5ZDRhYmMyNjFkOTM4MWFhYjFjZGQwYmYyODkzMmY3MDk5ZTdmNGQ2OWY1NDYyNDIwYzgyZDRiOWEyZmU0ZDczYWY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
