# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTBjOGVmZTcwOWM4NzVkZDY3NmQ5Y2QyYTA4YzVhOWI0YTg4ZGZkNTNiNGMwY2ZiNDAxMGVmZDI0ZWM5NGE2MjQwZGNiNTU0NDk5ODExN2Y2YWNiNzVkOWUzYmFmMjRmMzg4OTA5NTYyNGI4MTViM2YwOTJkOGQ2ZDA3YmQ1YjU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
